# Generated by Django 5.1.15 on 2026-02-24 06:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 6), ('news', 11), ('contact_info', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название видео', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на видео (YouTube, VK, Rutube и др.)', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание видео', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_url', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок новости', 'required': True}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Текст новости', 'required': True}), 9: ('wagtail.blocks.DateBlock', (), {'help_text': 'Дата публикации', 'required': True}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение новости', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 7), ('content', 8), ('date', 9), ('image', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название контакта', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Значение контакта', 'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'CSS класс иконки', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('value', 13), ('icon', 14)]], {})}),
        ),
    ]
