# Generated by Django 5.1.15 on 2026-02-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='О нас', help_text="Заголовок секции 'О нас'", max_length=200)),
                ('about_content', models.TextField(help_text='Текст описания')),
                ('address', models.CharField(help_text='Адрес', max_length=300)),
                ('email', models.EmailField(help_text='Email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Телефон', max_length=50)),
                ('vk_link', models.URLField(blank=True, help_text='Ссылка на VK')),
                ('youtube_link', models.URLField(blank=True, help_text='Ссылка на YouTube')),
                ('telegram_link', models.URLField(blank=True, help_text='Ссылка на Telegram')),
                ('contact_person', models.CharField(help_text='Контактное лицо', max_length=100)),
                ('contact_position', models.CharField(help_text='Должность контактного лица', max_length=100)),
            ],
            options={
                'verbose_name': 'Настройки футера',
                'verbose_name_plural': 'Настройки футера',
            },
        ),
    ]
