# Generated by Django 6.0.2 on 2026-02-26 18:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_footersettings'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Вводный текст')),
                ('content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название видео', 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'HTML код встраивания видео (iframe)', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание видео', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_embed', 4), ('description', 5)]], {})})),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('address', models.CharField(blank=True, help_text='Адрес', max_length=300)),
                ('phone', models.CharField(blank=True, help_text='Телефон', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254)),
                ('map_embed', models.TextField(blank=True, help_text='HTML код карты (iframe)')),
                ('content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('contact_info', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название контакта', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Значение контакта', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'CSS класс иконки', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('value', 3), ('icon', 4)]], {})})),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ExpertsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Вводный текст')),
                ('content', wagtail.fields.StreamField([('expert', 4), ('heading', 5), ('paragraph', 6), ('image', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Имя эксперта', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Фото эксперта', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Должность', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Биография', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('photo', 1), ('position', 2), ('bio', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 6: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'})})),
            ],
            options={
                'verbose_name': 'Эксперты',
                'verbose_name_plural': 'Эксперты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Вводный текст')),
            ],
            options={
                'verbose_name': 'Новости (индекс)',
                'verbose_name_plural': 'Новости (индекс)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(help_text='Дата публикации')),
                ('intro', models.TextField(blank=True, help_text='Краткое описание')),
                ('content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название видео', 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'HTML код встраивания видео (iframe)', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание видео', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_embed', 4), ('description', 5)]], {})})),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PartnersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Вводный текст')),
                ('content', wagtail.fields.StreamField([('partner', 4), ('heading', 5), ('paragraph', 6), ('image', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название партнёра', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Логотип партнёра', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Сайт партнёра', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1), ('description', 2), ('website', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 6: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'})})),
            ],
            options={
                'verbose_name': 'Партнёры',
                'verbose_name_plural': 'Партнёры',
            },
            bases=('wagtailcore.page',),
        ),
    ]
