# Generated by Django 6.0.2 on 2026-02-28 18:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutpage_contactpage_expertspage_newsindexpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 6), ('video_file', 9), ('audio_file', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название видео', 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'HTML код встраивания видео (iframe)', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание видео', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_embed', 4), ('description', 5)]], {}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Загрузите видео файл (mp4, webm, mov)', 'required': True}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Постер (обложка) для видео', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_file', 7), ('description', 5), ('poster', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название аудио', 'required': True}), 11: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Загрузите аудио файл (mp3, wav, ogg)', 'required': True}), 12: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание аудио', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 10), ('audio_file', 11), ('description', 12)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 6), ('video_file', 9), ('audio_file', 13), ('news', 18), ('contact_info', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название видео', 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'HTML код встраивания видео (iframe)', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание видео', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_embed', 4), ('description', 5)]], {}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Загрузите видео файл (mp4, webm, mov)', 'required': True}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Постер (обложка) для видео', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_file', 7), ('description', 5), ('poster', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название аудио', 'required': True}), 11: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Загрузите аудио файл (mp3, wav, ogg)', 'required': True}), 12: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание аудио', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 10), ('audio_file', 11), ('description', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок новости', 'required': True}), 15: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Текст новости', 'required': True}), 16: ('wagtail.blocks.DateBlock', (), {'help_text': 'Дата публикации', 'required': True}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение новости', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15), ('date', 16), ('image', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название контакта', 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Значение контакта', 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'CSS класс иконки', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('title', 19), ('value', 20), ('icon', 21)]], {})}),
        ),
    ]
