# Generated by Django 6.0.2 on 2026-02-28 19:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_aboutpage_content_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertspage',
            name='content',
            field=wagtail.fields.StreamField([('expert', 4), ('table', 5), ('heading', 6), ('paragraph', 7), ('image', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Имя эксперта', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Фото эксперта', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Должность', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Биография', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('photo', 1), ('position', 2), ('bio', 3)]], {}), 5: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 7: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'})}),
        ),
    ]
