# Generated by Django 5.1.15 on 2026-02-24 05:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageObjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HeritageObjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание объекта')),
                ('year_built', models.CharField(blank=True, max_length=50, verbose_name='Год постройки')),
                ('architectural_style', models.CharField(blank=True, max_length=100, verbose_name='Архитектурный стиль')),
                ('content', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 6), ('document', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название видео', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на видео (YouTube, VK, Rutube и др.)', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание видео', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_url', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название документа', 'required': True}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'PDF документ', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание документа', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('document', 8), ('description', 9)]], {})})),
            ],
            options={
                'verbose_name': 'Объект историко-архитектурного наследия',
                'verbose_name_plural': 'Объекты историко-архитектурного наследия',
            },
            bases=('wagtailcore.page',),
        ),
    ]
