# Generated by Django 6.0.2 on 2026-02-28 21:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageobjectpage',
            name='gallery',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение для галереи', 'icon': 'image'})}, help_text='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='heritageobjectpage',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='heritageobjectpage',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='heritageobjectpage',
            name='map_link',
            field=models.URLField(blank=True, help_text='Ссылка на Яндекс.Карты или другую карту', verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='heritageobjectpage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='heritageobjectpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 6), ('document', 10), ('comparison', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название видео', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на видео (YouTube, VK, Rutube и др.)', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание видео', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_url', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название документа', 'required': True}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'PDF документ', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание документа', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('document', 8), ('description', 9)]], {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение до (до реставрации)', 'required': True}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение после (после реставрации)', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Подпись', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('before_image', 11), ('after_image', 12), ('caption', 13)]], {})}),
        ),
    ]
