# Generated by Django 6.0.3 on 2026-06-08 17:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_objects', '0003_alter_heritageobjectpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritageobjectpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 6), ('document', 10), ('comparison', 14), ('panorama', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название видео', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на видео (YouTube, VK, Rutube и др.)', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание видео', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('video_url', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название документа', 'required': True}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'PDF документ', 'required': True}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание документа', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 7), ('document', 8), ('description', 9)]], {}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение до (до реставрации)', 'required': True}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение после (после реставрации)', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Подпись', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('before_image', 11), ('after_image', 12), ('caption', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название панорамы (необязательно)', 'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Файл панорамы 360° (изображение JPG/PNG из галереи)', 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание панорамы (необязательно)', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 15), ('panorama', 16), ('description', 17)]], {})}),
        ),
    ]
