@startsalt
{+
  {
    <!-- Верхний ряд -->
    {
      "<b>Главная (HomePage)</b>" | "<b>Список объектов (IndexPage)</b>"
      ---
      {
        [ Лого ] Меню...
        ---
        HERO Блок
        ---
        Видео | Текст
        ---
        Новости [...]
        ---
        Footer
      }
      |
      {
        Header
        ---
        H1: Объекты
        ---
        [ Карта Leaflet ]
        ---
        Карточка 1 | Карточка 2 | Карточка 3
        ---
        Footer
      }
    }
    
    <!-- Нижний ряд -->
    ^
    {
      "<b>Детали объекта (ObjectPage)</b>" | "<b>Новость (NewsPage)</b>"
      ---
      {
        Header
        ---
        H1: Название
        ---
        {
          Галерея []
          ---
          Описание...
          ---
          Блоки StreamField
        }
        |
        {
          Sticky Card:
          Адрес, Тел...
          [ Карта ]
        }
        ---
        Footer
      }
      |
      {
        Header
        ---
        Breadcrumbs
        ---
        H1: Новость
        [ Фото ]
        Текст новости...
        ---
        [ Назад ]
        ---
        Footer
      }
    }
  }
}
@endsalt